services:
  bot:
    build: .
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.disable_ipv6: "1"
      net.ipv6.conf.lo.disable_ipv6: "1"
    ports:
      - '127.0.0.1:1488:1488'
    volumes:
      - .:/app/project
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
