#!/bin/bash

# ==========================================
# 🚀 VLESS Shop Bot - Professional Installer
# ==========================================

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

PROJECT_DIR="vless-shopbot"
ENV_FILE=".env"
REPO_URL="https://github.com/Bogdan199719/myvlessbottg.git"

print_header() {
    echo -e "${GREEN}"
    echo "====================================================="
    echo "       VLESS SHOP BOT INSTALLATION WIZARD            "
    echo "====================================================="
    echo -e "${NC}"
}

check_dependencies() {
    echo -e "\n${CYAN}📦 Checking system dependencies...${NC}"
    
    deps=("git" "docker" "docker-compose" "nginx" "curl" "certbot")
    
    for dep in "${deps[@]}"; do
        if ! command -v $dep &> /dev/null; then
            echo -e "${YELLOW}Utility '$dep' not found. Installing...${NC}"
            if ! sudo apt-get update && sudo apt-get install -y $dep; then
               # Special handle for certbot if basic install fails
               if [ "$dep" == "certbot" ]; then
                   sudo apt-get install -y certbot python3-certbot-nginx
               fi
               # Check again
               if ! command -v $dep &> /dev/null; then
                   echo -e "${RED}Failed to install $dep. Please install it manually.${NC}"
               fi
            fi
        else
            echo -e "${GREEN}✔ $dep is installed.${NC}"
        fi
    done
}

setup_project() {
    echo -e "\n${CYAN}📂 Setting up project...${NC}"
    
    if [ ! -d "$PROJECT_DIR" ]; then
        echo -e "${YELLOW}Cloning repository...${NC}"
        echo -e "${YELLOW}Note: Since this is a PRIVATE repository, you need to provide credentials (username + token).${NC}"
        if ! git clone "$REPO_URL" "$PROJECT_DIR"; then
            echo -e "${RED}Failed to clone repository. Check your internet connection or permissions.${NC}"
            echo -e "${YELLOW}Tip: Ensure you use a Personal Access Token as the password.${NC}"
            exit 1
        fi
    else
        echo -e "${YELLOW}Project directory exists. Pulling latest changes...${NC}"
        cd "$PROJECT_DIR" || exit
        git pull ||  echo -e "${RED}Git pull failed, skipping update...${NC}"
        cd ..
    fi
}

configure_environment() {
    echo -e "\n${CYAN}⚙️ Configuration Setup${NC}"
    
    TARGET_ENV="$PROJECT_DIR/$ENV_FILE"
    
    if [ -f "$TARGET_ENV" ]; then
        echo -e "${YELLOW}.env file already exists. Skipping generation.${NC}"
        # Extract DOMAIN from existing .env for Nginx setup
        DOMAIN=$(grep "^DOMAIN=" "$TARGET_ENV" | cut -d '=' -f2)
    else
        echo -e "${GREEN}Creating .env file from template...${NC}"
        
        # Interactive Setup
        read -p "Enter Telegram Bot Token: " BOT_TOKEN
        read -p "Enter Admin Telegram ID: " ADMIN_ID
        read -p "Enter Domain (e.g., vpn.mysite.com): " DOMAIN
        read -p "Enter Email for SSL (letsencrypt): " EMAIL
        
        # Save EMAIL temporarily for certbot
        export CERT_EMAIL="$EMAIL"

        # Create .env file
        cat <<EOF > "$TARGET_ENV"
# Generated by install.sh
TELEGRAM_BOT_TOKEN=$BOT_TOKEN
ADMIN_TELEGRAM_ID=$ADMIN_ID
DOMAIN=$DOMAIN
PANEL_LOGIN=admin
PANEL_PASSWORD=admin
YOOKASSA_ENABLED=false
CRYPTOBOT_ENABLED=false
TONCONNECT_ENABLED=false
EOF
        echo -e "${GREEN}✔ .env file created successfully!${NC}"
    fi
}

setup_nginx_ssl() {
    echo -e "\n${CYAN}🔒 Setting up Nginx & SSL...${NC}"
    
    if [ -z "$DOMAIN" ]; then
        echo -e "${RED}Domain not set. Skipping Nginx setup.${NC}"
        return
    fi
    
    NGINX_CONF="/etc/nginx/sites-available/$PROJECT_DIR.conf"
    
    # Check if cert exists
    if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
        echo -e "${GREEN}✔ SSL certificate for $DOMAIN already exists.${NC}"
    else
        if [ -z "$CERT_EMAIL" ]; then
             read -p "Enter Email for SSL (letsencrypt): " CERT_EMAIL
        fi
        
        echo -e "${YELLOW}Obtaining SSL certificate...${NC}"
        sudo ufw allow 80/tcp
        sudo ufw allow 443/tcp
        
        sudo certbot --nginx -d "$DOMAIN" --email "$CERT_EMAIL" --agree-tos --non-interactive --redirect
    fi
    
    # Create Nginx Config (Reverse Proxy to Docker)
    echo -e "${YELLOW}Configuring Nginx Reverse Proxy...${NC}"
    cat <<EOF | sudo tee "$NGINX_CONF"
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:1488;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

    # Enable Site
    sudo ln -sfn "$NGINX_CONF" "/etc/nginx/sites-enabled/$PROJECT_DIR.conf"
    
    # Test and Reload
    sudo nginx -t && sudo systemctl reload nginx
    echo -e "${GREEN}✔ Nginx configured successfully!${NC}"
}

finalize_installation() {
    echo -e "\n${CYAN}🚀 Launching Docker Containers...${NC}"
    cd "$PROJECT_DIR" || exit
    
    sudo docker-compose down --remove-orphans
    if sudo docker-compose up -d --build; then
        echo -e "\n${GREEN}==============================================${NC}"
        echo -e "${GREEN}      🎉 Installation Successful! 🎉      ${NC}"
        echo -e "${GREEN}==============================================${NC}"
        echo -e "\nWeb Panel available at: https://$DOMAIN"
        echo -e "Initial Login/Pass: admin / admin"
        echo -e "Running in Docker."
    else
        echo -e "${RED}Docker Launch Failed! Check logs with 'docker-compose logs -f'${NC}"
    fi
}

# Main Execution Flow
print_header
check_dependencies
setup_project
configure_environment
setup_nginx_ssl
finalize_installation
