#!/bin/bash

# ==========================================
# 🚀 VLESS Shop Bot - Professional Installer
# ==========================================

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

PROJECT_DIR="vless-shopbot"
ENV_FILE=".env"
REPO_URL="https://github.com/Bogdan199719/myvlessbottg.git"

print_header() {
    echo -e "${GREEN}"
    echo "====================================================="
    echo "       VLESS SHOP BOT INSTALLATION WIZARD            "
    echo "====================================================="
    echo -e "${NC}"
}

check_dependencies() {
    echo -e "\n${CYAN}📦 Checking system dependencies...${NC}"
    
    deps=("git" "docker" "docker-compose" "curl")
    
    for dep in "${deps[@]}"; do
        if ! command -v $dep &> /dev/null; then
            echo -e "${YELLOW}Utility '$dep' not found. Installing...${NC}"
            if ! sudo apt-get update && sudo apt-get install -y $dep; then
               echo -e "${RED}Failed to install $dep. Please install it manually.${NC}"
               # Docker usually needs special handling, but for now apt is a fallback
            fi
        else
            echo -e "${GREEN}✔ $dep is installed.${NC}"
        fi
    done
}

setup_project() {
    echo -e "\n${CYAN}📂 Setting up project...${NC}"
    
    if [ ! -d "$PROJECT_DIR" ]; then
        echo -e "${YELLOW}Cloning repository...${NC}"
        echo -e "${YELLOW}Note: If this is a private repository, you will be asked for credentials.${NC}"
        if ! git clone "$REPO_URL" "$PROJECT_DIR"; then
            echo -e "${RED}Failed to clone repository. Check your internet connection or permissions.${NC}"
            exit 1
        fi
    else
        echo -e "${YELLOW}Project directory exists. Pulling latest changes...${NC}"
        cd "$PROJECT_DIR" || exit
        git pull
        cd ..
    fi
}

configure_environment() {
    echo -e "\n${CYAN}⚙️ Configuration Setup${NC}"
    
    TARGET_ENV="$PROJECT_DIR/$ENV_FILE"
    
    if [ -f "$TARGET_ENV" ]; then
        echo -e "${YELLOW}.env file already exists. Skipping generation.${NC}"
    else
        echo -e "${GREEN}Creating .env file from template...${NC}"
        
        # Interactive Setup
        read -p "Enter Telegram Bot Token: " BOT_TOKEN
        read -p "Enter Admin Telegram ID: " ADMIN_ID
        read -p "Enter Domain (e.g., vpn.mysite.com): " DOMAIN
        
        # Create .env file
        cat <<EOF > "$TARGET_ENV"
# Generated by install.sh
TELEGRAM_BOT_TOKEN=$BOT_TOKEN
ADMIN_TELEGRAM_ID=$ADMIN_ID
DOMAIN=$DOMAIN
PANEL_LOGIN=admin
PANEL_PASSWORD=admin
YOOKASSA_ENABLED=false
CRYPTOBOT_ENABLED=false
TONCONNECT_ENABLED=false
EOF
        echo -e "${GREEN}✔ .env file created successfully!${NC}"
    fi
}

finalize_installation() {
    echo -e "\n${CYAN}🚀 Launching Docker Containers...${NC}"
    cd "$PROJECT_DIR" || exit
    
    sudo docker-compose down --remove-orphans
    if sudo docker-compose up -d --build; then
        echo -e "\n${GREEN}==============================================${NC}"
        echo -e "${GREEN}      🎉 Installation Successful! 🎉      ${NC}"
        echo -e "${GREEN}==============================================${NC}"
        echo -e "\nWeb Panel used to be at https://$DOMAIN (Configure Nginx manually if needed via standard certbot)"
        echo -e "Bot is running in Docker."
    else
        echo -e "${RED}Docker Launch Failed! Check logs with 'docker-compose logs -f'${NC}"
    fi
}

# Main Execution Flow
print_header
check_dependencies
setup_project
configure_environment
finalize_installation
